### ISSUE TITLE
Please consider renaming to something less generic than zsh-completion

### ISSUE THREAD

**Issue by unixorn** [batect/batect-zsh-completion#31]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by charleskorn** [comment]
Hi @unixorn, would something like `batect-zsh-completion` be OK?

**Comment by unixorn** [comment]
Yes, that'd make it clear what it's a completion for, thanks.

**Comment by charleskorn** [comment]
Done - thanks again for the suggestion.
